name: awesome_gallery_saver
description: A flutter plugin project for stroing image or file to gallery, support Andorid & Ios.
version: 0.0.6
homepage: https://github.com/huhx/flutter_gallery_saver.git

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.huhx.gallerysaver
        pluginClass: AwesomeGallerySaverPlugin
      ios:
        pluginClass: AwesomeGallerySaverPlugin
